import express from 'express'
import path from 'path'
import logger from 'morgan'
import cookieParser from 'cookie-parser'
import bodyParser from 'body-parser'
import methodOverride from 'method-override'
import session from 'express-session'
import compression from 'compression'
import connectMongo from 'connect-mongo'
import routers from './routers'
import $ from './utils'
import models from './models'
const app = express()
const MongoStore = connectMongo(session)