
export const RECEIVE_ARTICLE_LIST = 'RECEIVE_ARTICLE_LIST'
export const ADD_ARTICLE_ITEM = 'ADD_ARTICLE_ITEM'
export const UPDATE_ARTICLE_ITEM = 'UPDATE_ARTICLE_ITEM'
export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const RECOVER_ARTICLE = 'RECOVER_ARTICLE'
