
export const RECEIVE_COMMENT_LIST = 'RECEIVE_COMMENT_LIST'
export const ADD_COMMENT_ITEM = 'ADD_COMMENT_ITEM'
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const RECOVER_COMMENT = 'RECOVER_COMMENT'