
export const RECEIVE_ARTICLE_LIST = 'RECEIVE_ARTICLE_LIST'
export const RECEIVE_ARTICLE_ITEM = 'RECEIVE_ARTICLE_ITEM'
export const RECEIVE_TRENDING = 'RECEIVE_TRENDING'
export const MODIFY_LIKE_STATUS = 'MODIFY_LIKE_STATUS'